name: Deploy to Oracle Cloud

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for Gradle
      run: chmod +x ./gradlew

    - name: Build JAR with Gradle
      run: ./gradlew clean build

    - name: Copy JAR to Oracle Cloud server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: build/libs/*.jar
        target: ~/deploy/

    - name: Deploy and Restart Java App on Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Stopping existing Java processes..."
          pkill -f 'java -jar' || echo "No process to kill"

          echo "Starting new application..."
          mkdir -p ~/logs
          cd ~/deploy
          latest_jar=$(ls -t *.jar | head -n 1)
          nohup java -jar "$latest_jar" > ~/logs/output.log 2>&1 &

          echo "Application deployed and running in background."
